# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/dewei/Documents/xvc-pynq-z2/example/hw/source/constraints/top.xdc

# Block Designs: bd/xvc_system/xvc_system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xvc_system || ORIG_REF_NAME==xvc_system} -quiet] -quiet

# IP: bd/xvc_system/ip/xvc_system_axi_jtag_0_0/xvc_system_axi_jtag_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xvc_system_axi_jtag_0_0 || ORIG_REF_NAME==xvc_system_axi_jtag_0_0} -quiet] -quiet

# IP: bd/xvc_system/ip/xvc_system_processing_system7_0_0/xvc_system_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xvc_system_processing_system7_0_0 || ORIG_REF_NAME==xvc_system_processing_system7_0_0} -quiet] -quiet

# IP: bd/xvc_system/ip/xvc_system_processing_system7_0_axi_periph_0/xvc_system_processing_system7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xvc_system_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==xvc_system_processing_system7_0_axi_periph_0} -quiet] -quiet

# IP: bd/xvc_system/ip/xvc_system_rst_processing_system7_0_100M_0/xvc_system_rst_processing_system7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xvc_system_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==xvc_system_rst_processing_system7_0_100M_0} -quiet] -quiet

# IP: bd/xvc_system/ip/xvc_system_auto_pc_0/xvc_system_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xvc_system_auto_pc_0 || ORIG_REF_NAME==xvc_system_auto_pc_0} -quiet] -quiet

# XDC: bd/xvc_system/ip/xvc_system_processing_system7_0_0/xvc_system_processing_system7_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==xvc_system_processing_system7_0_0 || ORIG_REF_NAME==xvc_system_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/xvc_system/ip/xvc_system_rst_processing_system7_0_100M_0/xvc_system_rst_processing_system7_0_100M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==xvc_system_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==xvc_system_rst_processing_system7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/xvc_system/ip/xvc_system_rst_processing_system7_0_100M_0/xvc_system_rst_processing_system7_0_100M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==xvc_system_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==xvc_system_rst_processing_system7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/xvc_system/ip/xvc_system_rst_processing_system7_0_100M_0/xvc_system_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/xvc_system/ip/xvc_system_auto_pc_0/xvc_system_auto_pc_0_ooc.xdc

# XDC: bd/xvc_system/xvc_system_ooc.xdc
